#!/bin/bash

echo "🚀 DEPLOY PARA PRODUÇÃO (RAILWAY + VERCEL)"
echo ""

echo "📋 PRÉ-REQUISITOS:"
echo "1. Instale Railway CLI: npm install -g @railway/cli"
echo "2. Instale Vercel CLI: npm install -g vercel"
echo "3. Faça login: railway login && vercel login"
echo ""

echo "🔧 CONFIGURAÇÃO DAS VARIÁVEIS DE AMBIENTE NO RAILWAY:"
echo ""
echo "=== BACKEND SERVICE ==="
echo "MONGO_URL=mongodb://mongo:sua_senha@mongodb.railway.internal:27017"
echo "DB_NAME=crm_production"
echo "PORT=8001"
echo "WHATSAPP_SERVICE_URL=https://sua-whatsapp-service-url.up.railway.app"
echo ""
echo "=== WHATSAPP SERVICE ==="
echo "FASTAPI_URL=https://sua-backend-url.up.railway.app"
echo "PORT=3001"
echo ""
echo "=== FRONTEND (VERCEL) ==="
echo "REACT_APP_BACKEND_URL=https://sua-backend-url.up.railway.app"
echo ""

echo "📦 STEPS PARA DEPLOY:"
echo ""
echo "1️⃣ DEPLOY BACKEND:"
echo "   railway link [seu-projeto-backend]"
echo "   railway up --service backend"
echo ""
echo "2️⃣ DEPLOY WHATSAPP SERVICE:"
echo "   cd whatsapp-service"
echo "   railway link [seu-projeto-whatsapp]"
echo "   railway up --service whatsapp"
echo "   cd .."
echo ""
echo "3️⃣ DEPLOY FRONTEND:"
echo "   vercel --prod"
echo ""

echo "⚠️  IMPORTANTE:"
echo "• Configure todas as variáveis de ambiente no Railway dashboard"
echo "• Atualize as URLs após cada deploy"
echo "• O WhatsApp service precisa da URL do backend"
echo "• O backend precisa da URL do WhatsApp service"
echo "• O frontend precisa da URL do backend"